plugins {
    id 'com.android.application'
}

android {
    namespace 'com.arshia.espanol'
    compileSdk 36

    defaultConfig {
        applicationId 'com.arshia.espanol'
        minSdk 26
        targetSdk 36
        versionCode 1
        versionName '1.0.0'
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}
