plugins {
    id 'com.android.application'
}

android {
    namespace 'com.arshia.espanol'
    compileSdk 36

    defaultConfig {
        applicationId 'com.arshia.espanol'
        minSdk 26
        targetSdk 36
        versionCode 3
        versionName '1.0.2'
    }

    signingConfigs {
        personal {
            storeFile file('../signing/arshia-espanol.jks')
            storePassword 'arshia-spanish'
            keyAlias 'arshia-espanol'
            keyPassword 'arshia-spanish'
        }
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            signingConfig signingConfigs.personal
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}
